from __future__ import annotations

from enum import Enum


class AppState(str, Enum):
    IDLE = "IDLE"
    AUDIO_SELECTED = "AUDIO_SELECTED"
    RECORDING = "RECORDING"
    RECORDING_TRANSCRIBING = "RECORDING_TRANSCRIBING"
    TRANSCRIBING_FILE = "TRANSCRIBING_FILE"
    FINALIZING_RECORDING = "FINALIZING_RECORDING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"
